champ_to_role = {
    "Warwick": ["top", "jungle"],
    "Urgot": ["top"],
    "Chogath": ["top"],
    "Heimerdinger": ["top"],
    "DrMundo": ["top"],
    "Yorick": ["top"],
    "Fiora": ["top"],
    "Riven": ["top"],
    "Kayle": ["top"],
    "Ornn": ["top"],
    "Vayne": ["top", "adc"],
    "Kennen": ["top"],
    "Kled": ["top"],
    "Ryze": ["top", "mid"],
    "Volibear": ["top", "jungle"],
    "Mordekaiser": ["top"],
    "Singed": ["top"],
    "Olaf": ["top"],
    "Darius": ["top"],
    "Cassiopeia": ["top", "mid"],
    "Malphite": ["top"],
    "Aatrox": ["top"],
    "Garen": ["top"],
    "Nasus": ["top"],
    "Sett": ["top"],
    "Irelia": ["top", "mid"],
    "Quinn": ["top"],
    "Gwen": ["top", "jungle"],
    "Vladimir": ["top", "mid"],
    "Rengar": ["top", "jungle"],
    "Shen": ["top"],
    "Sylas": ["top", "mid"],
    "Renekton": ["top"],
    "Camille": ["top"],
    "Poppy": ["top", "jungle", "supp"],
    "Trundle": ["top", "jungle"],
    "Illaoi": ["top"],
    "Teemo": ["top"],
    "Ambessa": ["top"],
    "Akali": ["top", "mid"],
    "Gnar": ["top"],
    "Gangplank": ["top"],
    "Smolder": ["top", "adc"],
    "Jayce": ["top"],
    "KSante": ["top"],
    "Yasuo": ["top", "mid"],
    "Pantheon": ["top", "jungle", "mid", "supp"],
    "Jax": ["top"],
    "Yone": ["top", "mid"],
    "Sion": ["top"],
    "Tryndamere": ["top"],
    "Gragas": ["top", "jungle"],
    "Rumble": ["top"],
    "Amumu": ["jungle"],
    "Belveth": ["jungle"],
    "Briar": ["jungle"],
    "Diana": ["jungle", "mid"],
    "Elise": ["jungle", "supp"],
    "Ekko": ["jungle", "mid"],
    "Evelynn": ["jungle"],
    "Fiddlesticks": ["jungle"],
    "Graves": ["jungle"],
    "Hecarim": ["jungle"],
    "Ivern": ["jungle"],
    "JarvanIV": ["jungle"],
    "Karthus": ["jungle"],
    "Kayn": ["jungle"],
    "Khazix": ["jungle"],
    "Kindred": ["jungle"],
    "LeeSin": ["jungle"],
    "Lillia": ["jungle"],
    "MasterYi": ["jungle"],
    "Nunu": ["jungle"],
    "Nocturne": ["jungle"],
    "Naafiri": ["jungle"],
    "Nidalee": ["jungle"],
    "Rammus": ["jungle"],
    "RekSai": ["jungle"],
    "Shaco": ["jungle", "supp"],
    "Shyvana": ["jungle"],
    "Skarner": ["jungle"],
    "Sejuani": ["jungle"],
    "Taliyah": ["jungle", "mid"],
    "Talon": ["jungle", "mid"],
    "Udyr": ["jungle"],
    "Vi": ["jungle"],
    "Viego": ["jungle"],
    "MonkeyKing": ["jungle"],
    "XinZhao": ["jungle"],
    "Zac": ["jungle"],
    "Zed": ["jungle", "mid"],
    "Ahri": ["mid"],
    "Viktor": ["mid"],
    "Syndra": ["mid"],
    "Orianna": ["mid"],
    "Anivia": ["mid"],
    "Annie": ["mid"],
    "Velkoz": ["mid", "supp"],
    "Galio": ["mid"],
    "Brand": ["mid", "supp"],
    "Xerath": ["mid", "supp"],
    "Vex": ["mid"],
    "Lissandra": ["mid"],
    "Lux": ["mid", "supp"],
    "Veigar": ["mid"],
    "Malzahar": ["mid"],
    "Hwei": ["mid"],
    "AurelionSol": ["mid"],
    "Qiyana": ["mid"],
    "Akshan": ["mid"],
    "Aurora": ["mid"],
    "Kassadin": ["mid"],
    "Fizz": ["mid"],
    "Zoe": ["mid"],
    "TwistedFate": ["mid"],
    "Azir": ["mid"],
    "Katarina": ["mid"],
    "Leblanc": ["mid"],
    "Mel": ["mid", "supp"],
    "Jinx": ["adc"],
    "Draven": ["adc"],
    "Ezreal": ["adc"],
    "Caitlyn": ["adc"],
    "MissFortune": ["adc"],
    "Kaisa": ["adc"],
    "Tristana": ["adc"],
    "Sivir": ["adc"],
    "Lucian": ["adc"],
    "Jhin": ["adc"],
    "Senna": ["adc", "supp"],
    "Kalista": ["adc"],
    "Twitch": ["adc"],
    "Corki": ["adc"],
    "Zeri": ["adc"],
    "Xayah": ["adc"],
    "Aphelios": ["adc"],
    "Varus": ["adc"],
    "Ashe": ["adc"],
    "KogMaw": ["adc"],
    "Nilah": ["adc"],
    "Samira": ["adc"],
    "Ziggs": ["adc"],
    "Thresh": ["supp"],
    "Nami": ["supp"],
    "Lulu": ["supp"],
    "Janna": ["supp"],
    "Blitzcrank": ["supp"],
    "Leona": ["supp"],
    "Soraka": ["supp"],
    "Sona": ["supp"],
    "Nautilus": ["supp"],
    "Zyra": ["supp"],
    "Yuumi": ["supp"],
    "Swain": ["supp"],
    "TahmKench": ["supp"],
    "Taric": ["supp"],
    "Renata": ["supp"],
    "Seraphine": ["supp"],
    "Neeko": ["supp"],
    "Rakan": ["supp"],
    "Rell": ["supp"],
    "Milio": ["supp"],
    "Morgana": ["supp"],
    "Braum": ["supp"],
    "Karma": ["supp"],
    "Alistar": ["supp"],
    "Bard": ["supp"],
    "Pyke": ["supp"],
    "Maokai": ["supp"],
    "Zilean": ["supp"]
}
